#!/usr/bin/env python


#takes the output files generated by surfacespectra.py
# and plot premultiplied energy spectrum and
# one-dimensional spectrum plots 

# Make sure to have the directory "figureSpectra"

#Copyright by Matteo Montecchia
import os
import matplotlib.pyplot as plt 
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
import pylab as p
import numpy as np
import numpy.matlib
from matplotlib import rc
rc('text', usetex = True)

#load files
Euup = np.loadtxt('Euup.txt')
Eppp = np.loadtxt('Eppp.txt')
kzEuup = np.loadtxt('kzEuup.txt')




kz = np.loadtxt('kz.txt')
yp = np.loadtxt('yp.txt')

Retau = 481.43642
nu = 1.3764e-5
utau = Retau*nu
Nz = 128
lambdazp = 2*np.pi/kz[0:Nz/2+1]*Retau

#------------------- Premultiplied spectrum contour plot ---------------------------------#
#only for velocity up to now

fig=plt.figure(0)
ax = fig.add_subplot(111)
plt.subplots_adjust(top = 0.95, bottom = 0.2, left = 0.2, right = 0.95)
[lambdazpp,ypp] = np.meshgrid(lambdazp[0:Nz/2],yp)
cp = plt.contourf(lambdazpp,ypp,np.abs(kzEuup), shading = 'gouraud')
plt.colorbar()
cp2 = plt.contour(lambdazpp,ypp,np.abs(kzEuup), shading = 'gouraud')

plt.rc('font', family = 'serif')
plt.yscale('log')
plt.xscale('log')
plt.ylim([1,2e2])
plt.xlim([55,Retau])
plt.xlabel('$\\lambda_z^+$',fontsize=25)
plt.ylabel('$y^+$',fontsize=25)
plt.tick_params(axis='both',which='major',labelsize=20.0)
ax.set_xticks([55,100,200,300,400,519])
ax.xaxis.set_ticklabels(['55','100','200','300','400','519'])
plt.grid()
plt.savefig('figureSpectra/kzEuu',format="eps",bbox_inches='tight')

#-----------------------------------------------------------------------------------------#

#------------- Plot velocity and pressure spectra at y+ = 13,200 and centreline ----------#

plt.figure(1)
plt.subplots_adjust(top = 0.95, bottom = 0.2, left = 0.2, right = 0.95)
plt.rc('font', family = 'serif')

plt.loglog(kz[0:Nz/2]/Retau,Euup[1,0:Nz/2],'--r', label = '$\\beta_p =1.0, y^+ \\approx 13$')
plt.loglog(kz[0:Nz/2]/Retau,Euup[15,0:Nz/2],'--c', label = '$\\beta_p =1.0, y^+ \\approx 200$')
plt.loglog(kz[0:Nz/2]/Retau,Euup[-1,0:Nz/2],'--b', label = '$\\beta_p =1.0, y^+ \\approx 542$')

a = np.array([0.02, 0.12])
b = 0.00002*a**(-5/3)
plt.loglog(a,b,'k--', label = '$C k_z^{-5/3}$')
plt.legend(loc='lower left',frameon=False,fontsize = 'large')
plt.xlabel('$k_z^+$',fontsize=25)
plt.ylabel('$E_{uu}^{1D} / u_\\tau^2$',fontsize=25)
plt.tick_params(axis='both',which='major',labelsize=20.0)
plt.grid()
plt.savefig('figureSpectra/Euu',format="eps",bbox_inches='tight')

plt.figure(2)
plt.subplots_adjust(top = 0.95, bottom = 0.2, left = 0.2, right = 0.95)
plt.rc('font', family = 'serif')

plt.loglog(kz[0:Nz/2]/Retau,Eppp[1,0:Nz/2],'--r', label = '$\\beta_p = 1.0, y^+ \\approx 13$')
plt.loglog(kz[0:Nz/2]/Retau,Eppp[15,0:Nz/2],'--c', label = '$\\beta_p = 1.0, y^+ \\approx 200$')
plt.loglog(kz[0:Nz/2]/Retau,Eppp[-1,0:Nz/2],'--b', label = '$\\beta_p =1.0, y^+ \\approx 542$')

a = np.array([0.019, 0.12])
b = 6e-8*a**(-7/3)
plt.loglog(a,b,'k--', label = '$C k_z^{-7/3}$')
plt.legend(loc='lower left',frameon=False,fontsize = 'large')
plt.xlabel('$k_z^+$',fontsize=25)
plt.ylabel('$E_{pp}^{1D} / u_\\tau^4$',fontsize=25)
plt.tick_params(axis='both',which='major',labelsize=20.0)
plt.grid()
plt.savefig('figureSpectra/Epp',format="eps",bbox_inches='tight')

plt.show()
